name: jaspr_markdown
description: A Markdown renderer for Jaspr. It lets you use Jaspr components in
  Markdown. You can import components like MDX.
version: 0.1.6
homepage: https://github.com/siesdart/jaspr_markdown
repository: https://github.com/siesdart/jaspr_markdown
issue_tracker: https://github.com/siesdart/jaspr_markdown/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  html: ^0.15.6
  jaspr: ^0.21.3
  markdown: ^7.3.0

dev_dependencies:
  mockito: ^5.5.0
  test: ^1.26.3
  very_good_analysis: ^9.0.0

topics:
  - jaspr
  - web
  - markdown
